### ISSUE TITLE
biblatex compatibility

### ISSUE THREAD

**Issue by cgnieder** [cgnieder/enotez#11]
**[Original report](https://bitbucket.org/cgnieder/enotez/issue/11) by Clemens Niederberger (Bitbucket: [cgnieder](https://bitbucket.org/cgnieder), GitHub: [cgnieder](https://github.com/cgnieder)).**

----------------------------------------

See https://tex.stackexchange.com/a/304464/

**Comment by moewew** [comment]
I stumbled about this again because of https://tex.stackexchange.com/q/597359/35864. 

I'm wondering whether it would be possible to simply offer a new key to inject arbitrary code before the text of an endnote is typeset.

Actually, due to the nature of endnotes, for `biblatex` compatibility it would be enough to be able to locally set a certain toggle to true for `\printendnotes`. (I tried `\AtEveryEndnotesList`, but that is apparently not grouped, so the toggle setting leaks out. Plus it is meant for text...) So we could also make to with a `\AtEveryEndnotesList` version that is for arbitrary code and whose effect is limited via grouping to the current list.

```latex
\documentclass{report}
\usepackage{biblatex-chicago}

\usepackage{enotez}
\setenotez{list-heading=\section*{#1}}
\let\footnote=\endnote

\newcommand*{\printendnotesbiblatex}{%
  \begingroup
  \toggletrue{blx@footnote}
  \printendnotes
  \endgroup
}

\addbibresource{biblatex-examples.bib}

\begin{document}
\chapter{Alpha}
Some text \autocite{sigfridsson}.

Some text with footnote.\footnote{\autocite{worman}}

Some text \autocite{sigfridsson}.

\printendnotesbiblatex

\chapter{Bravo}
Some text \autocite{worman}.

Some text \autocite{geer}.

\printendnotesbiblatex
\end{document}
```

**Comment by cgnieder** [comment]
Thanks, the group is now implemented and `\AtEveryEndnotesList{\toggletrue{blx@footnote}}` works as expected.

**Comment by gusbrs** [comment]
Might I add a request here that `\DeclareTemplateCode {enotez-list} {list}` also be grouped for the same reason?

**Comment by cgnieder** [comment]
@gusbrs thanks. Added.

**Comment by gusbrs** [comment]
@cgnieder Thank you!
